openapi: "3.0.0"
info:
  title: Campaign Composer REST API
  version: "1.1.0"

security:
  - apiKeyAuth: []

paths:
  /campaigns:
    get:
      operationId: listCampaigns
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/campaign.yaml#/campaign'
  /campaigns/{campaignId}/documents:
    get:
      summary: Get a list of metadata for all documents
      operationId: listDocuments
      parameters:
        - $ref: '#/components/parameters/campaignId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/document.yaml#/documentMeta'
  /campaigns/{campaignId}/documents/{docId}:
    get:
      operationId: getDocument
      parameters:
        - $ref: '#/components/parameters/campaignId'
        - $ref: '#/components/parameters/docId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './models/document.yaml#/document'
  /campaigns/{campaignId}/maps:
    get:
      summary: Get a list of all maps
      operationId: listMaps
      parameters:
        - $ref: '#/components/parameters/campaignId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/map.yaml#/cMap'
  /campaigns/{campaignId}/maps/{mapId}:
    get:
      operationId: getMap
      parameters:
        - $ref: '#/components/parameters/campaignId'
        - $ref: '#/components/parameters/mapId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './models/map.yaml#/cMap'
  /campaigns/{campaignId}/maps/{mapId}/background:
    get:
      operationId: getMapBackground
      parameters:
        - $ref: '#/components/parameters/campaignId'
        - $ref: '#/components/parameters/mapId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './models/map.yaml#/mapBackground'
  /campaigns/{campaignId}/maps/{mapId}/metadata:
    get:
      operationId: getMapMetadata
      parameters:
        - $ref: '#/components/parameters/campaignId'
        - $ref: '#/components/parameters/mapId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './models/map.yaml#/mapMetadata'

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  parameters:
    campaignId:
      name: campaignId
      in: path
      required: true
      schema:
        type: integer
    docId:
      name: docId
      in: path
      required: true
      schema:
        type: string
    mapId:
      name: mapId
      in: path
      required: true
      schema:
        type: string
