openapi: "3.0.0"
info:
  title: Campaign Composer REST API
  version: "1.1.0"

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

security:
  - apiKeyAuth: []

paths:
  /documents:
    get:
      summary: Get a list of metadata for all documents
      operationId: listDocuments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/document.yaml#/documentMeta'
              examples:
                default:
                  value:
                    - id: 590B91E5-4520-40CE-A5B5-8FE019486EF8
                      title: Document title
                      type: entity
                      created: '2022-06-14T04:35:29Z'
                      updated: '2022-06-14T04:35:29Z'
  /documents/{docId}:
    get:
      operationId: getDocument
      parameters:
      - name: docId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './models/document.yaml#/document'
              examples:
                default:
                  value:
                    id: 590B91E5-4520-40CE-A5B5-8FE019486EF8
                    title: Document title
                    created: '2022-06-14T04:35:29Z'
                    updated: '2022-06-14T04:35:29Z'
                    contents:
                      - id: F90BA1E5-4520-40BE-A5B5-8FE019486EF8
                        type: heading
                        contents: 'Section heading'
                      - id: A90BA1E5-4520-40BE-A5B5-8FE019486EF8
                        type: paragraph
                        contents: 'Section body'
  /maps:
    get:
      summary: Get a list of all maps
      operationId: listMaps
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/map.yaml#/cMap'
              examples:
                default:
                  value:
                    id: 590B91E5-4520-40CE-A5B5-8FA219486EF8
                    title: Map title
                    created: '2022-06-14T04:35:29Z'
                    updated: '2022-06-14T04:35:29Z'
  /maps/{mapId}:
    get:
      operationId: getMap
      parameters:
      - name: mapId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './models/map.yaml#/cMap'