composerLink:
  type: object
  required:
    - id
  properties:
    id:
      type: string
    _t:
      discriminator:
        propertyName: "_t"
        mapping:
          doc: '#/docLink'
          map: '#/mapLink'
          ext: '#/extLink'
      type: 
        oneOf:
          - $ref: '#/docLink'
          - $ref: '#/mapLink'
          - $ref: '#/extLink'

docLink:
  type: object
  required:
    - docId
  properties:
    docId:
      type: string
    startBlockId:
      type: string

mapLink:
  type: object
  required:
    - mapId
  properties:
    mapId:
      type: string

extLink:
  type: object
  required:
    - uri
  properties:
    uri:
      type: string